# Generated by Django 4.2.3 on 2023-07-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradesense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MinArbitrage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('arbitrage_amount', models.FloatField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='trades',
            name='min_arbitrage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='trades',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
