# Generated by Django 4.2.3 on 2023-07-27 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradesense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptos',
            name='sort',
            field=models.CharField(default='price', max_length=300),
        ),
    ]
