# Generated by Django 4.2.3 on 2023-07-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradesense', '0003_rename_minarbitrage_arbitragethreshold_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArbitrageThreshold',
        ),
        migrations.AddField(
            model_name='crypto',
            name='arbitrage_threshold_amount',
            field=models.FloatField(default=0),
        ),
    ]
